### ISSUE TITLE
Text sizing changes

### ISSUE THREAD

**Issue by dcndr** [SubjectiveLabs/SubjectiveAssembly#37]
<img width="1073" alt="image" src="https://github.com/SubjectiveLabs/SubjectiveAssembly/assets/56007854/caae6410-678c-44c2-8248-58ba84e52439">

Make red the same size as blue, and make green larger than red by a small amount.

**Comment by circles-png** [comment]
![image](https://github.com/SubjectiveLabs/SubjectiveAssembly/assets/27723996/3f776d29-a8a6-4b59-b1a2-e9c252328b11)
`School name`:
```css
.text-2xl {
  font-size: 1.5rem/* 24px */;
  line-height: 2rem/* 32px */;
}
```
`Welcome to`:
```css
.text-xl {
  font-size: 1.25rem/* 20px */;
  line-height: 1.75rem/* 28px */;
}
```
